### <font color='cian'>ENTREGA DE LA CONSIGNA #3 </font>

* COMISIÓN: <font color='cian'>23678CaC - Big Data /Data Anlaytics</font>

<font color='cian'>Archivos complementarios en FILES > Mi Proyecto > c23678-MariaBelenAreal-TPIntegrador. Ahí se encuentran las capturas de pantalla y archivos .sql</font>

----------------------------------------

<font color='cian'>1. Los nombres elegidos se visualizan en el ítem 2.</font>

----------------------------------------

<font color='cian'> 2. Se generó la tabla en DB Browser for SQLite </font>

----------------------------------------

In [ ]:
df_1 = _deepnote_execute_sql('-- USE Netflix;\n-- Crear la tabla \'oscar\'\nCREATE TABLE IF NOT EXISTS oscar (\n    id_oscar INTEGER PRIMARY KEY AUTOINCREMENT,\n    id_inf INTEGER,\n    id_res INTEGER,\n    id_content INTEGER,\n    title_oscar VARCHAR(128),\n    year_ceremony INTEGER,\n    category VARCHAR(256),\n    name VARCHAR(256),\n    winner TINYINT,\n    Directed_by VARCHAR(128),\n    Based_on VARCHAR(512),\n    Starring VARCHAR(512),\n    Distributed_by VARCHAR(256),\n    Budget VARCHAR(128),\n    Budget_Mill DOUBLE,\n    Box_office VARCHAR(128),\n    Box_office_Mill DOUBLE,\n    IMDB DOUBLE,\n    Metascore INTEGER,\n    Rotten_Tomatoes INTEGER\n);', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_1

<font color='cian'> 3. Ver imágenes complemetarias. </font>

----------------------------------------

<font color='cian'> 4. Reutilice el código que realicé para la consigna #2 en el ítem 3 pero adaptandola para un archivo csv.</font>

In [ ]:
import pandas as pd

oscar = pd.read_csv('oscar.csv')


########################
import pandas as pd

df = pd.read_csv('oscar.csv')

columnas = list(oscar.columns)

resultados = pd.DataFrame(columns=['Columna', 'NotNull', 'Vacios', 'Null', 'ValoresDistintos'])

for columna in columnas:
    notnull_count = df[columna].notnull().sum()
    vacios_count = (df[columna] == '').sum()
    null_count = df[columna].isnull().sum()
    valores_distintos = df[columna].nunique()
    
    resultados = resultados.append({'Columna': columna, 'NotNull': notnull_count, 'Vacios': vacios_count, 
    'Null': null_count, 'ValoresDistintos': valores_distintos}, ignore_index=True)

resultados.set_index('Columna', inplace=True)

resultados_transpose = resultados.transpose()

display(resultados_transpose)

In [ ]:
df_2 = _deepnote_execute_sql('-- A\nSELECT c.title_content AS Título, c.type AS Tipo_de_Contenido\nFROM content AS c\nJOIN production AS p ON c.id_content = p.id_content\nWHERE p.runtime > 90 AND p.language = \'French\'\nORDER BY c.title_content ASC;\n\n-- B\nSELECT c.title_content AS Título\nFROM content AS c\nJOIN production AS p ON c.id_content = p.id_content\nWHERE p.runtime > 70 AND p.director IS NOT NULL AND p.country IS NOT NULL\nORDER BY c.title_content ASC;\n\n-- C\nSELECT p.country AS País_de_Origen, p.genre AS Género, SUM(p.runtime) AS Total_Runtime\nFROM production AS p\nWHERE p.country IN (\'United States\', \'India\', \'Japan\', \'Spain\', \'Mexico\')\nGROUP BY p.country, p.genre\nORDER BY p.country ASC;\n\n-- D\nSELECT c.title_content AS Título, c.type AS Tipo_de_Contenido\nFROM content AS c\nJOIN oscar AS o ON c.id_content = o.id_content\nWHERE c.type = \'movie\' AND c.listed_in LIKE \'%Drama%\' AND o.category = \'Best Picture\' AND o.year BETWEEN 2010 AND 2020;\n\n-- E\nSELECT c.title_content AS Título, p.genre AS Género\nFROM content AS c\nJOIN production AS p ON c.id_content = p.id_content\nWHERE p.language = \'English\' AND p.imdb_score BETWEEN 7 AND 9;\n\n-- F\nSELECT p.genre AS Género, COUNT(*) AS Cantidad\nFROM production AS p\nGROUP BY p.genre\nORDER BY Cantidad DESC, Género ASC;\n\n-- G\nSELECT DISTINCT c.title_content AS Título, (p.budget / p.box_office) AS Ratio_Budget_BoxOffice\nFROM content AS c\nJOIN production AS p ON c.id_content = p.id_content\nWHERE p.imdb_score BETWEEN 7 AND 9 AND p.budget IS NOT NULL AND p.box_office IS NOT NULL;\n\n-- H\nSELECT c.title_content AS Título, o.year AS Año_Ganador\nFROM content AS c\nJOIN oscar AS o ON c.id_content = o.id_content\nWHERE o.category = \'Best Picture\'\nORDER BY o.year DESC;\n\n-- I\nSELECT c.title_content AS Título, o.year AS Año_Ceremonia\nFROM content AS c\nJOIN oscar AS o ON c.id_content = o.id_content\nWHERE c.id_content IN (SELECT id_content FROM production WHERE imdb_score BETWEEN 7 AND 9)\nORDER BY Título ASC, Año_Ceremonia DESC;\n\n-- J\nSELECT c.title_content AS Título, o.category AS Categoría, p.genre AS Género, p.runtime AS Duración, p.imdb_score AS Puntuación_IMDB, p.premiere AS Estreno, o.year AS Año_Ceremonia\nFROM content AS c\nJOIN oscar AS o ON c.id_content = o.id_content\nJOIN production AS p ON c.id_content = p.id_content\nWHERE c.type = \'movie\' AND c.country = \'United States\' AND o.won = 1;\n\n-- K\nSELECT c.title_content AS Título, o.category AS Categoría, o.year AS Año_Ceremonia\nFROM content AS c\nJOIN oscar AS o ON c.id_content = o.id_content\nWHERE c.type = \'movie\' AND c.country = \'United States\' AND o.won = 0;\n', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_2

In [ ]:
df_3 = _deepnote_execute_sql('-- Punto 7\n-- I\nSELECT type AS Tipo_de_Contenido, COUNT(*) AS Cantidad\nFROM content\nGROUP BY type;\n\n-- II\nSELECT c.title_content AS Título, c.listed_in AS Categoría\nFROM content AS c\nJOIN production AS p ON c.id_content = p.id_content\nWHERE p.runtime = 90 AND UPPER(p.country) = \'UNITED STATES\'\nORDER BY c.title_content ASC;\n\n-- III\nSELECT c.title_content AS Título, c.listed_in AS Categoría\nFROM content AS c\nJOIN production AS p ON c.id_content = p.id_content\nWHERE (UPPER(p.country) LIKE \'%UNITED STATES%\' OR UPPER(p.country) = \'UNITED STATES\')\n  AND (UPPER(c.listed_in) LIKE \'%HORROR MOVIE%\' OR UPPER(c.listed_in) = \'HORROR MOVIE\')\nORDER BY c.title_content ASC;\n\n-- IV\nSELECT c.title_content AS Título, o.year AS Año_Oscar\nFROM content AS c\nJOIN oscar AS o ON c.id_content = o.id_content\nWHERE o.category = \'Best Picture\' AND o.metascore >= 85;\n', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_3