### <font color='cian'>ENTREGA DE LA CONSIGNA #2 </font>

* COMISIÓN: <font color='cian'>23678CaC - Big Data /Data Anlaytics</font>


----------------------------------------

 <font color='cian'>Contruí la tabla en python con la información que extraje de SQLite. En el caso de la cantidad de columnas realice un código en python para obtenerlo.</font>

In [ ]:
### Import
import sqlite3
import pandas as pd

In [ ]:
conexion = sqlite3.connect('netflix.db')
cursor = conexion.cursor()

tabla_info = cursor.execute("PRAGMA table_info(production)").fetchall()

numero_de_columnas = len(tabla_info)

conexion.close()

In [ ]:
columns = pd.MultiIndex.from_tuples([
    ('Netflix.db', 'Tabla'),
    ('Netflix.db', 'Clave Primaria'),
    ('Netflix.db', 'Clave Foránea'),
    ('Production', 'Total de filas'),
    ('Production', 'Total de columnas')
])

df = pd.DataFrame(columns=columns)

df.loc[0] = ['production', 'id_production', 'id_content', 551, numero_de_columnas]

display(df)

   Netflix.db                                  Production
        Tabla Clave Primaria Clave Foránea Total de filas Total de columnas
0  production  id_production    id_content            551                 8

----------------------------------------

 <font color='cian'>Recorro para todas las columnas la tabla y obtengo la cantidad de valores pedidos. Luego construyo una tabla con dicha información y le doy el formato solicitado.</font>

In [ ]:
conexion = sqlite3.connect('netflix.db')

columnas = ['id_production', 'id_content', 'title_production', 'genre', 'premiere', 'runtime', 'imdb_score', 'language']

resultados = pd.DataFrame(columns=['Columna', 'NotNull', 'Vacios', 'Null', 'ValoresDistintos'])

for columna in columnas:
    query_notnull = f"SELECT COUNT(*) FROM production WHERE {columna} IS NOT NULL;"
    query_vacios = f"SELECT COUNT(*) FROM production WHERE {columna} = '';"
    query_null = f"SELECT COUNT(*) FROM production WHERE {columna} = '';"
    query_valores_distintos = f"SELECT COUNT(DISTINCT {columna}) FROM production;"
    
    notnull_count = conexion.execute(query_notnull).fetchone()[0]
    vacios_count = conexion.execute(query_vacios).fetchone()[0]
    null_count = conexion.execute(query_null).fetchone()[0]
    valores_distintos = conexion.execute(query_valores_distintos).fetchone()[0]
    
    resultados = resultados.append({'Columna': columna, 'NotNull': notnull_count, 'Vacios': vacios_count, 
    'Null': null_count, 'ValoresDistintos': valores_distintos}, ignore_index=True)

conexion.close()

resultados.rename(columns={'Columna': 'Netflix - production'}, inplace=True)
resultados.set_index('Netflix - production', inplace=True)
resultados_transpose = resultados.transpose()

display(resultados_transpose)

/tmp/ipykernel_223222/1648500932.py:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  resultados = resultados.append({'Columna': columna, 'NotNull': notnull_count, 'Vacios': vacios_count,
/tmp/ipykernel_223222/1648500932.py:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  resultados = resultados.append({'Columna': columna, 'NotNull': notnull_count, 'Vacios': vacios_count,
/tmp/ipykernel_223222/1648500932.py:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  resultados = resultados.append({'Columna': columna, 'NotNull': notnull_count, 'Vacios': vacios_count,
/tmp/ipykernel_223222/1648500932.py:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  resultados = resultados.append({'Columna': columna, 'NotNull': notnull_count, 'Vacios': vacios_count,
/tmp/ipykernel_223222/1648500932.py:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  resultados = resultados.append({'Columna': columna, 'NotNull': notnull_count, 'Vacios': vacios_count,
/tmp/ipykernel_223222/1648500932.py:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  resultados = resultados.append({'Columna': columna, 'NotNull': notnull_count, 'Vacios': vacios_count,
/tmp/ipykernel_223222/1648500932.py:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  resultados = resultados.append({'Columna': columna, 'NotNull': notnull_count, 'Vacios': vacios_count,
/tmp/ipykernel_223222/1648500932.py:18: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  resultados = resultados.append({'Columna': columna, 'NotNull': notnull_count, 'Vacios': vacios_count,

Netflix - production,id_production,id_content,title_production,genre,premiere,runtime,imdb_score,language
NotNull,551,551,551,551,551,551,551,551
Vacios,0,0,0,0,0,0,0,0
Null,0,0,0,0,0,0,0,0
ValoresDistintos,551,551,551,110,370,118,52,37

<font color='cian'>Este ítem lo pude correr directamente en DB Browser for SQLite (ya que lo realice desde la notebook de mi trabajo a diferencia de los otros puntos, ya que en mi notebook principal no me funcionó este programa).</font>

In [ ]:
conexion = sqlite3.connect('netflix.db')

cursor = conexion.cursor()


sentencia_create_nueva_tabla = """
CREATE TABLE production_new (
  id_produccion INTEGER PRIMARY KEY AUTOINCREMENT,
  id_contenido INTEGER DEFAULT NULL,
  titulo_produccion VARCHAR(50) DEFAULT NULL,
  genero VARCHAR(50) DEFAULT NULL,
  estreno VARCHAR(50) DEFAULT NULL,
  duracion INTEGER DEFAULT NULL,
  puntuacion_imdb REAL DEFAULT NULL,
  idioma VARCHAR(50) DEFAULT NULL
);
"""

cursor.execute(sentencia_create_nueva_tabla)

sentencia_copiar_datos = "INSERT INTO production_new SELECT * FROM production"
cursor.execute(sentencia_copiar_datos)

# sentencia_eliminar_tabla_original = "DROP TABLE production"
# cursor.execute(sentencia_eliminar_tabla_original)
# sentencia_renombrar_tabla = "ALTER TABLE production_new RENAME TO production"
# cursor.execute(sentencia_renombrar_tabla)

tabla_info_new = cursor.execute("PRAGMA table_info(production_new)").fetchall()

conexion.commit()
conexion.close()

display(tabla_info_new)

[(0, 'id_produccion', 'INTEGER', 0, None, 1),
 (1, 'id_contenido', 'INTEGER', 0, 'NULL', 0),
 (2, 'titulo_produccion', 'VARCHAR(50)', 0, 'NULL', 0),
 (3, 'genero', 'VARCHAR(50)', 0, 'NULL', 0),
 (4, 'estreno', 'VARCHAR(50)', 0, 'NULL', 0),
 (5, 'duracion', 'INTEGER', 0, 'NULL', 0),
 (6, 'puntuacion_imdb', 'REAL', 0, 'NULL', 0),
 (7, 'idioma', 'VARCHAR(50)', 0, 'NULL', 0)]

<font color='cian'> Código en DB Browser </font>

In [ ]:
df_1 = _deepnote_execute_sql('-- SELECT * FROM production\n\n-- A\nSELECT type AS Tipo, title_content AS Título, country AS País, rating AS Clasificación, duration AS Duración, listed_in AS Categoría\nFROM content;\n\n-- B\nSELECT id_content AS ID_contenido, title_production AS Título, genre AS Género, runtime AS Duración, imdb_score AS Puntuación_IMDB\nFROM production;\n\n-- C   (No me funcionó)\nSELECT id_content AS ID_contenido, type AS Tipo, title_content AS Título, director AS Director, cast AS Reparto, rating AS Clasificación, duration AS Duración, listed_in AS Categoría\nFROM content\nWHERE country LIKE \'%Argentina%\';\n\n-- D\nSELECT id_production AS ID, title_production AS Título, genre AS Género, language AS Idioma, imdb_score AS Puntuación_IMDB\nFROM production\nWHERE imdb_score > 7.5;\n\n-- E\nSELECT id_content AS ID, type AS Tipo, title_content AS Título, listed_in AS Categoría\nFROM content\nWHERE rating = \'TV-Y\' OR rating = \'TV-Y7\' OR rating = \'TV-G\' OR rating = \'G\';\n\n-- F\nSELECT id_production AS ID, title_production AS Título, genre AS Género\nFROM production\nWHERE runtime <= 105 AND runtime >= 60;\n\n-- G\nSELECT type AS Tipo, rating AS Clasificación, COUNT(*) AS Cantidad\nFROM content\nGROUP BY type, rating\nORDER BY rating, type;\n\n--H\nSELECT language AS Idioma, COUNT(*) AS Cantidad\nFROM production\nWHERE language IN (\'Portuguese\', \'French\', \'German\', \'Italian\', \'Spanish\')\nGROUP BY language\nORDER BY Cantidad DESC;\n', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_1


----------------------------------------

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=da85ffec-f3f8-46e6-a8a8-28433ab3181c' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>